versions:
  # master:
  #   linux: x64Linux3gcc4.8.2
  #   windows: x64Win64VS2015
  # develop:
  #   linux: x64Linux3gcc4.8.2
  #   windows: x64Win64VS2015
  release/7.3.0:
    linux: x64Linux3gcc4.8.2
    # windows: x64Win64VS2015
  # release/6.1.2:
  #   linux: x64Linux2.6gcc4.4.5
  #   windows: x64Win64VS2012
